remote_theme: artlogic/jekyll-theme-iota
plugins:
   - jekyll-relative-links
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-sitemap   
title: 50
description: Sawks is turning 50, come and party with us
author:
  name: "Sawks"
  email: "50@sawks.com"
relative_links:
  enabled: true
  collections: true
github:
  is_project_page: false